name: Build

on:
  push:
    paths:
      - 'src/**'
    branches:
      - master
  pull_request:
    paths:
      - 'src/**'
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Build packages
        run: pnpm build

      - name: Release to dev tag
        run: |
          commit_message=$(git rev-parse --short HEAD)
          git add .
          git commit -m "build: $commit_message"
          git push